### PR TITLE
Made requirements.txt

### PR DESCRIPTION
**Pull request by LogMoss**
Issue #22 
I made the `requirements.txt` file.

### CODE REVIEW

**Comment by LogMoss** [comment]
After trying to generate it with some tool, I finally made it manually. Also broke the OS when making that :)

**Comment by LakshyAAAgrawal** [comment]
Thank you very much for the PR. It looks good to me. But I will be able to test only tomorrow. In the meanwhile, feel free to look into other issues!

**Comment by LakshyAAAgrawal** [comment]
That is sad temporarily, but I am pretty sure you had good fun trying to
figure out what went wrong and fixing it back. Not to mention the learning
you got. I hope it was a good learning experience for you. Feel free to
contact me regarding any issues you may face related to this project, or
even if you need help with your OS.

**Comment by LogMoss** [comment]
Yeah had fun for 8h also learned alot, but going to reinstall OS since I messed it up quite badly

**Comment by LakshyAAAgrawal** [comment]
Thanks a lot @erkska. I hope you have been able to fix your OS..

**Pull request merged**
